include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Errors
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    constant_identifier_names: true
    control_flow_in_finally: true
    directives_ordering: true
    empty_constructor_bodies: true
    hash_and_equals: true
    implementation_imports: true
    library_prefixes: true
    list_remove_unrelated_type: true
    no_duplicate_case_values: true
    non_constant_identifier_names: true
    null_closures: true
    only_throw_errors: true
    prefer_generic_function_type_aliases: true
    prefer_relative_imports: true
    super_goes_last: true
    test_types_in_equals: true
    throw_in_finally: true
    type_annotate_public_apis: false
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_null_aware_assignments: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unrelated_type_equality_checks: true
    valid_regexps: true

    # Warnings
    always_declare_return_types: true
    #always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_js_rounded_ints: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_setters_without_getters: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_as_parameter_names: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    #avoid_dynamic_calls: true
    camel_case_extensions: true
    close_sinks: true
    comment_references: true
    curly_braces_in_flow_control_structures: true
    empty_statements: true
    file_names: true
    library_names: true
    lines_longer_than_80_chars: false
    overridden_fields: true
    package_names: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_with_message: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_contains: true
    prefer_double_quotes: false
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_initializing_formals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    public_member_api_docs: false
    require_trailing_commas: false
    slash_for_doc_comments: true
    sort_constructors_first: false
    sort_unnamed_constructors_first: false
    type_init_formals: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_new: true
    unnecessary_overrides: true
    unnecessary_this: true
    use_function_type_syntax_for_parameters: true
    use_full_hex_values_for_flutter_colors: true
    use_is_even_rather_than_modulo: true
    use_key_in_widget_constructors: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true